# Generated by Django 5.1.2 on 2026-08-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutsession',
            name='payment_url',
            field=models.URLField(blank=True, default='', max_length=2048),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_created', 'Session Created'), ('webhook_received', 'Webhook Received'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed')], db_index=True, max_length=30)),
                ('provider_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.checkoutsession')),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
