# Generated by Django 5.1.2 on 2026-08-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_payment_url_and_payment_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
