# Generated by Django 5.1.2 on 2026-08-17 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_checkoutsession_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='event_type',
            field=models.CharField(choices=[('session_created', 'Session Created'), ('session_queried', 'Session Queried'), ('webhook_received', 'Webhook Received'), ('callback_processed', 'Callback Processed'), ('payment_confirmed', 'Payment Confirmed'), ('payment_failed', 'Payment Failed')], db_index=True, max_length=30),
        ),
    ]
